_target_: models.ddpm.GaussianDDPM
T: ${noise_steps}
sampling_timesteps: ${sampling_timesteps}
denoiser_module: ${denoiser_module}
width: ${dataset.width}
height: ${dataset.height}
input_channels: ${dataset.channels}