_target_: models.unet2.UNetModel
in_channels: ${dataset.channels}
model_channels: 128
out_channels: 3
num_res_blocks: 2
attention_resolutions: {16,8}
dropout: 0.0
channel_mult: {1, 2, 3, 4}
num_classes: null
use_checkpoint: False
num_heads: 4
num_heads_upsample: -1
use_scale_shift_norm: True