model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

data_params:
  data_path: "Data/celeba/img_align_celeba"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"