_target_: data.datasets.DDPMDataset
data_path: /home/work/reality/hojae/genAI/data/afhq
train_batch_size: 64
val_batch_size:  64
patch_size: 128
width: 128
height : 128
channels: 3
num_workers: 8
pin_memory: True