_target_: data.datasets.DDPMDataset
data_path: /home/work/reality/hojae/genAI/data/celeba
train_batch_size: 64
val_batch_size:  64
patch_size: 64
width: 64
height : 64
channels: 3
num_workers: 4
pin_memory: True