_target_: models.unet_2.UNet
channels: [1, 32, 64, 128, 256]
kernel_sizes: [3, 3, 3, 3]
strides: [1, 1, 1, 1]
paddings: [1, 1, 1, 1]
p_dropouts: [0.1, 0.1, 0.1, 0.1]
time_embed_size: 100  #did not found this hp on the paper
downsample: true
