_target_: data.datasets.DDPMDataset
data_path: /home/work/reality/hojae/genAI/Diffusion-Based/data/celeba
train_batch_size: 32
val_batch_size:  32
patch_size: 256
width: 256
height : 256
channels: 3
num_workers: 4
pin_memory: True