_target_: data.datasets.DDPMDataset
data_path: /home/work/reality/hojae/genAI/Diffusion-Based/data/celeba
train_batch_size: 128
val_batch_size:  128
patch_size: 128
width: 128
height : 128
channels: 3
num_workers: 4
pin_memory: True