_target_: data.datasets.DDPMDataset
data_path: /home/work/reality/hojae/genAI/data/flower
train_batch_size: 128
val_batch_size:  128
patch_size: 64
width: 64
height : 64
channels: 3
num_workers: 8
pin_memory: True