_target_: data.datasets.DDPMDataset
data_path: /home/work/reality/hojae/genAI/data/mnist
train_batch_size: 128
val_batch_size:  128
patch_size: 64
width: 64
height : 64
channels: 1
num_workers: 2
pin_memory: True