defaults:
  - _self_
  - model: unet
  - diffusion: gaussian
  - dataset: celeba256
  - optimizer: adam_ddpm

steps: ${diffusion.noise_steps}  # T
sampling_timesteps: 100
ckpt: null
seed: 1337  # random seed

# Defaul Configuration
ema_rate: 0.9999
log_interval: 10
save_interval: 1000
learn_sigma: False