_target_: models.unet.UNet
channels: [3, 128, 256, 256, 384]
kernel_sizes: [3, 3, 3, 3]
strides: [1, 1, 1, 1]
paddings: [1, 1, 1, 1]
p_dropouts: [0.1, 0.1, 0.1, 0.1]
time_embed_size: 100  #did not found this hp on the paper
downsample: true